name: Lint Markdown

on:
  push:
    branchs:
      - main
  pull_request:
    branchs:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint-md-github-action
        uses: lint-md/github-action@v0.1.1

